// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.dmitr.romashov.grpc_server;

public interface InfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 value = 1;</code>
   */
  int getValue();
}
