// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.dmitr.romashov.grpc_server;

public interface InfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 multipliers = 1;</code>
   */
  java.util.List<java.lang.Integer> getMultipliersList();
  /**
   * <code>repeated int32 multipliers = 1;</code>
   */
  int getMultipliersCount();
  /**
   * <code>repeated int32 multipliers = 1;</code>
   */
  int getMultipliers(int index);
}
