// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.dmitr.romashov.grpc_server;

/**
 * Protobuf type {@code InfoResponse}
 */
public  final class InfoResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:InfoResponse)
    InfoResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InfoResponse.newBuilder() to construct.
  private InfoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InfoResponse() {
    multipliers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InfoResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              multipliers_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            multipliers_.add(input.readInt32());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
              multipliers_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              multipliers_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        multipliers_ = java.util.Collections.unmodifiableList(multipliers_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dmitr.romashov.grpc_server.FactorizationServiceProto.internal_static_InfoResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dmitr.romashov.grpc_server.FactorizationServiceProto.internal_static_InfoResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dmitr.romashov.grpc_server.InfoResponse.class, com.dmitr.romashov.grpc_server.InfoResponse.Builder.class);
  }

  public static final int MULTIPLIERS_FIELD_NUMBER = 1;
  private java.util.List<java.lang.Integer> multipliers_;
  /**
   * <code>repeated int32 multipliers = 1;</code>
   */
  public java.util.List<java.lang.Integer>
      getMultipliersList() {
    return multipliers_;
  }
  /**
   * <code>repeated int32 multipliers = 1;</code>
   */
  public int getMultipliersCount() {
    return multipliers_.size();
  }
  /**
   * <code>repeated int32 multipliers = 1;</code>
   */
  public int getMultipliers(int index) {
    return multipliers_.get(index);
  }
  private int multipliersMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getMultipliersList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(multipliersMemoizedSerializedSize);
    }
    for (int i = 0; i < multipliers_.size(); i++) {
      output.writeInt32NoTag(multipliers_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < multipliers_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(multipliers_.get(i));
      }
      size += dataSize;
      if (!getMultipliersList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      multipliersMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dmitr.romashov.grpc_server.InfoResponse)) {
      return super.equals(obj);
    }
    com.dmitr.romashov.grpc_server.InfoResponse other = (com.dmitr.romashov.grpc_server.InfoResponse) obj;

    boolean result = true;
    result = result && getMultipliersList()
        .equals(other.getMultipliersList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMultipliersCount() > 0) {
      hash = (37 * hash) + MULTIPLIERS_FIELD_NUMBER;
      hash = (53 * hash) + getMultipliersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dmitr.romashov.grpc_server.InfoResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dmitr.romashov.grpc_server.InfoResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dmitr.romashov.grpc_server.InfoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dmitr.romashov.grpc_server.InfoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dmitr.romashov.grpc_server.InfoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dmitr.romashov.grpc_server.InfoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dmitr.romashov.grpc_server.InfoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dmitr.romashov.grpc_server.InfoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dmitr.romashov.grpc_server.InfoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dmitr.romashov.grpc_server.InfoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dmitr.romashov.grpc_server.InfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dmitr.romashov.grpc_server.InfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dmitr.romashov.grpc_server.InfoResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code InfoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:InfoResponse)
      com.dmitr.romashov.grpc_server.InfoResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dmitr.romashov.grpc_server.FactorizationServiceProto.internal_static_InfoResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dmitr.romashov.grpc_server.FactorizationServiceProto.internal_static_InfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dmitr.romashov.grpc_server.InfoResponse.class, com.dmitr.romashov.grpc_server.InfoResponse.Builder.class);
    }

    // Construct using com.dmitr.romashov.grpc_server.InfoResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      multipliers_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dmitr.romashov.grpc_server.FactorizationServiceProto.internal_static_InfoResponse_descriptor;
    }

    public com.dmitr.romashov.grpc_server.InfoResponse getDefaultInstanceForType() {
      return com.dmitr.romashov.grpc_server.InfoResponse.getDefaultInstance();
    }

    public com.dmitr.romashov.grpc_server.InfoResponse build() {
      com.dmitr.romashov.grpc_server.InfoResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.dmitr.romashov.grpc_server.InfoResponse buildPartial() {
      com.dmitr.romashov.grpc_server.InfoResponse result = new com.dmitr.romashov.grpc_server.InfoResponse(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        multipliers_ = java.util.Collections.unmodifiableList(multipliers_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.multipliers_ = multipliers_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dmitr.romashov.grpc_server.InfoResponse) {
        return mergeFrom((com.dmitr.romashov.grpc_server.InfoResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dmitr.romashov.grpc_server.InfoResponse other) {
      if (other == com.dmitr.romashov.grpc_server.InfoResponse.getDefaultInstance()) return this;
      if (!other.multipliers_.isEmpty()) {
        if (multipliers_.isEmpty()) {
          multipliers_ = other.multipliers_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureMultipliersIsMutable();
          multipliers_.addAll(other.multipliers_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dmitr.romashov.grpc_server.InfoResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dmitr.romashov.grpc_server.InfoResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<java.lang.Integer> multipliers_ = java.util.Collections.emptyList();
    private void ensureMultipliersIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        multipliers_ = new java.util.ArrayList<java.lang.Integer>(multipliers_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int32 multipliers = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getMultipliersList() {
      return java.util.Collections.unmodifiableList(multipliers_);
    }
    /**
     * <code>repeated int32 multipliers = 1;</code>
     */
    public int getMultipliersCount() {
      return multipliers_.size();
    }
    /**
     * <code>repeated int32 multipliers = 1;</code>
     */
    public int getMultipliers(int index) {
      return multipliers_.get(index);
    }
    /**
     * <code>repeated int32 multipliers = 1;</code>
     */
    public Builder setMultipliers(
        int index, int value) {
      ensureMultipliersIsMutable();
      multipliers_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 multipliers = 1;</code>
     */
    public Builder addMultipliers(int value) {
      ensureMultipliersIsMutable();
      multipliers_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 multipliers = 1;</code>
     */
    public Builder addAllMultipliers(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureMultipliersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, multipliers_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 multipliers = 1;</code>
     */
    public Builder clearMultipliers() {
      multipliers_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:InfoResponse)
  }

  // @@protoc_insertion_point(class_scope:InfoResponse)
  private static final com.dmitr.romashov.grpc_server.InfoResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dmitr.romashov.grpc_server.InfoResponse();
  }

  public static com.dmitr.romashov.grpc_server.InfoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InfoResponse>
      PARSER = new com.google.protobuf.AbstractParser<InfoResponse>() {
    public InfoResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new InfoResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InfoResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InfoResponse> getParserForType() {
    return PARSER;
  }

  public com.dmitr.romashov.grpc_server.InfoResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

