# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import grpc_pb2 as grpc__pb2


class FactorizationServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getMultipliers = channel.unary_unary(
        '/FactorizationService/getMultipliers',
        request_serializer=grpc__pb2.InfoRequest.SerializeToString,
        response_deserializer=grpc__pb2.InfoResponse.FromString,
        )


class FactorizationServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getMultipliers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FactorizationServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getMultipliers': grpc.unary_unary_rpc_method_handler(
          servicer.getMultipliers,
          request_deserializer=grpc__pb2.InfoRequest.FromString,
          response_serializer=grpc__pb2.InfoResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'FactorizationService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
